# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-11 17:02
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20191109_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
